# Generated by Django 4.1.3 on 2022-11-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO stro
        """)
    ]
